const COUNTRIES = {
  AD: 'Andorra',
  AE: 'Emirati Arabi Uniti',
  AF: 'Afghanistan',
  AG: 'Antigua e Barbuda',
  AI: 'Anguilla',
  AL: 'Albania',
  AM: 'Armenia',
  AN: 'Antille olandesi',
  AO: 'Angola',
  AQ: 'Antartico',
  AR: 'Argentina',
  AS: 'Samoa americane',
  AT: 'Austria',
  AU: 'Australia',
  AW: 'Aruba',
  AX: 'Isole Åland',
  AZ: 'Azerbaigian',
  BA: 'Bosnia-Erzegovina',
  BB: 'Barbados',
  BD: 'Bangladesh',
  BE: 'Belgio',
  BF: 'Burkina Faso',
  BG: 'Bulgaria',
  BH: 'Bahrein',
  BI: 'Burundi',
  BJ: 'Benin',
  BL: 'Saint Barthelémy',
  BM: 'Bermuda',
  BN: 'Brunei Darussalam',
  BO: 'Bolivia',
  BQ: 'Bonaire, Sant\'Eustachio e Saba',
  BR: 'Brasile',
  BS: 'Bahamas',
  BT: 'Bhutan',
  BU: 'Birmania',
  BV: 'Isola Bouvet',
  BW: 'Botswana',
  BY: 'Bielorussia',
  BZ: 'Belize',
  CA: 'Canada',
  CC: 'Isole Cocos/Keeling',
  CD: 'Repubblica democratica del Congo',
  CF: 'Repubblica Centrafricana',
  CG: 'Congo',
  CH: 'Svizzera',
  CI: 'Costa D\'Avorio',
  CK: 'Isole Cook',
  CL: 'Cile',
  CM: 'Camerun',
  CN: 'Cina',
  CO: 'Colombia',
  CR: 'Costa Rica',
  CS: 'Cecoslovacchia',
  CU: 'Cuba',
  CV: 'Capo Verde',
  CW: 'Curaçao',
  CX: 'Isola Christmas (Australia)',
  CY: 'Cipro',
  CZ: 'Repubblica Ceca',
  DD: 'Repubblica democratica tedesca',
  DE: 'Germania',
  DJ: 'Gibuti',
  DK: 'Danimarca',
  DM: 'Dominica',
  DO: 'Repubblica Dominicana',
  DZ: 'Algeria',
  EC: 'Ecuador',
  EE: 'Estonia',
  EG: 'Egitto',
  EH: 'Sahara occidentale',
  ER: 'Eritrea',
  ES: 'Spagna',
  ET: 'Etiopia',
  FI: 'Finlandia',
  FJ: 'Figi',
  FK: 'Isole Falkland',
  FM: 'Micronesia',
  FO: 'Isole Fær Øer',
  FR: 'Francia',
  FX: 'Francia metropolitana',
  GA: 'Gabon',
  GB: 'Regno Unito',
  GD: 'Grenada',
  GE: 'Georgia',
  GF: 'Guiana francese',
  GG: 'Guernsey',
  GH: 'Ghana',
  GI: 'Gibilterra',
  GL: 'Groenlandia',
  GM: 'Gambia',
  GN: 'Guinea',
  GP: 'Guadalupa',
  GQ: 'Guinea equatoriale',
  GR: 'Grecia',
  GS: 'Georgia del sud',
  GT: 'Guatemala',
  GU: 'Guam',
  GW: 'Guinea-Bissau',
  GY: 'Guiana',
  HK: 'Hong Kong',
  HM: 'Isole Heard e McDonald',
  HN: 'Honduras',
  HR: 'Croazia',
  HT: 'Haiti',
  HU: 'Ungheria',
  ID: 'Indonesia',
  IE: 'Irlanda',
  IL: 'Israele',
  IM: 'Isola di Man',
  IN: 'India',
  IO: 'Territorio britannico dell\'Oceano Indiano',
  IQ: 'Iraq',
  IR: 'Iran',
  IS: 'Islanda',
  IT: 'Italia',
  JE: 'Jersey',
  JM: 'Giamaica',
  JO: 'Giordania',
  JP: 'Giappone',
  KE: 'Kenya',
  KG: 'Kirghizistan',
  KH: 'Cambogia',
  KI: 'Kiribati',
  KM: 'Comore',
  KN: 'Saint Kitts e Nevis',
  KP: 'Repubblica democratica popolare di Corea',
  KR: 'Repubblica di Corea',
  KW: 'Kuwait',
  KY: 'Isole Cayman',
  KZ: 'Kazakistan',
  LA: 'Laos',
  LB: 'Libano',
  LC: 'Saint Lucia',
  LI: 'Liechtenstein',
  LK: 'Sri Lanka',
  LR: 'Liberia',
  LS: 'Lesotho',
  LT: 'Lituania',
  LU: 'Lussemburgo',
  LV: 'Lettonia',
  LY: 'Libia',
  MA: 'Marocco',
  MC: 'Monaco',
  MD: 'Moldavia',
  ME: 'Montenegro',
  MF: 'Saint Martin (parte francese)',
  MG: 'Madagascar',
  MH: 'Isole Marshall',
  MK: 'Macedonia (Ex-Repubblica Iugoslava di)',
  ML: 'Mali',
  MM: 'Myanmar (ex Birmania)',
  MN: 'Mongolia',
  MO: 'Macao',
  MP: 'Isole Marianne settentrionali',
  MQ: 'Martinica',
  MR: 'Mauritania',
  MS: 'Montserrat',
  MT: 'Malta',
  MU: 'Maurizio',
  MV: 'Maldive',
  MW: 'Malawi',
  MX: 'Messico',
  MY: 'Malesia',
  MZ: 'Mozambico',
  NA: 'Namibia',
  NC: 'Nuova Caledonia',
  NE: 'Niger',
  NF: 'Isola Norfolk',
  NG: 'Nigeria',
  NI: 'Nicaragua',
  NL: 'Paesi Bassi',
  NO: 'Norvegia',
  NP: 'Nepal',
  NR: 'Nauru',
  NT: 'zona neutra',
  NU: 'Niue',
  NZ: 'Nuova Zelanda',
  OM: 'Oman',
  PA: 'Panama',
  PE: 'Perù',
  PF: 'Polinesia Francese',
  PG: 'Papua Nuova Guinea',
  PH: 'Filippine',
  PK: 'Pakistan',
  PL: 'Polonia',
  PM: 'Saint-Pierre e Miquelon',
  PN: 'Pitcairn',
  PR: 'Portorico',
  PS: 'Territorio Palestinese, occupato',
  PT: 'Portogallo',
  PW: 'Palau',
  PY: 'Paraguay',
  QA: 'Qatar',
  RE: 'Riunione',
  RO: 'Romania',
  RS: 'Serbia',
  RU: 'Russia',
  RW: 'Ruanda',
  SA: 'Arabia Saudita',
  SB: 'Isole Salomone',
  SC: 'Seychelles',
  SD: 'Sudan',
  SE: 'Svezia',
  SG: 'Singapore',
  SH: 'Sant\'Elena',
  SI: 'Slovenia',
  SJ: 'Svalbard e Isola Jan Mayen',
  SK: 'Slovacchia',
  SL: 'Sierra Leone',
  SM: 'San Marino',
  SN: 'Senegal',
  SO: 'Somalia',
  SR: 'Suriname',
  SS: 'Sudan del sud',
  ST: 'Sao Tomé e Principe',
  SU: 'URSS',
  SV: 'El Salvador',
  SX: 'Sint Maarten (parte olandese)',
  SY: 'Siria',
  SZ: 'Swaziland',
  TC: 'Isole Turks e Caicos',
  TD: 'Ciad',
  TF: 'Terre australi francesi',
  TG: 'Togo',
  TH: 'Tailandia',
  TJ: 'Tagichistan',
  TK: 'Tokelau',
  TL: 'Timor Est (Timor-Leste)',
  TM: 'Turkmenistan',
  TN: 'Tunisia',
  TO: 'Tonga',
  TP: 'Timor orientale',
  TR: 'Turchia',
  TT: 'Trinidad e Tobago',
  TV: 'Tuvalu',
  TW: 'Taiwan',
  TZ: 'Tanzania',
  UA: 'Ucraina',
  UG: 'Uganda',
  UM: 'Isole minori degli Stati Uniti',
  UN: 'Paese indeterminato',
  US: 'Stati Uniti',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VA: 'Santa Sede (Stato della Città del Vaticano)',
  VC: 'Saint Vincent e Grenadine',
  VE: 'Venezuela',
  VG: 'Isole Vergini britanniche',
  VI: 'Isole Vergini americane',
  VN: 'Vietnam',
  VU: 'Vanuatu',
  WF: 'Wallis e Futuna',
  WS: 'Samoa',
  YD: 'Yemen democratico',
  YE: 'Yemen',
  YT: 'Mayotte',
  YU: 'Iugoslavia',
  ZA: 'Africa del sud',
  ZM: 'Zambia',
  ZR: 'Zaire',
  ZW: 'Zimbabwe',
};

const resolveCountryByCode = (code) => COUNTRIES[code];

const keyBy = (array, field, multiEntry = false) => {
  const res = {};
  array.forEach((item) => {
    if (multiEntry) {
      if (!res[item[field]]) {
        res[item[field]] = [];
      }
      res[item[field]].push(item);
    } else {
      res[item[field]] = item;
    }
  });
  return res;
};

module.exports = {
  resolveCountryByCode,
  keyBy,
};
